

SELECT TABLE_NAME
FROM LaborStatisticsDB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE';

SELECT COLUMN_NAME, DATA_TYPE
FROM LaborStatisticsDB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'datatype';

SELECT COLUMN_NAME, DATA_TYPE
FROM LaborStatisticsDB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'seasonal';

SELECT COLUMN_NAME, DATA_TYPE
FROM LaborStatisticsDB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'supersector';

SELECT COLUMN_NAME, DATA_TYPE
FROM LaborStatisticsDB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'footnote';

SELECT COLUMN_NAME, DATA_TYPE
FROM LaborStatisticsDB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'january_2017';

SELECT COLUMN_NAME, DATA_TYPE
FROM LaborStatisticsDB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'annual_2016';

SELECT COLUMN_NAME, DATA_TYPE
FROM LaborStatisticsDB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'series';

SELECT COLUMN_NAME, DATA_TYPE
FROM LaborStatisticsDB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'period';

SELECT COLUMN_NAME, DATA_TYPE
FROM LaborStatisticsDB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'industry';